[de]
    label  = "Deutsch"
    title  = "Stefan Biermann – DIY Tech & HomeLab"
    weight = 1

    [de.params.sidebar]
        subtitle = "Smart Home, 3D-Druck, IoT, Linux, Balkon-Solar und Maker-Projekte"
